// <auto-generated />
using ASP.NET_CRUD_example_2.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ASP.NET_CRUD_example_2.Migrations
{
    [DbContext(typeof(PostgreSqlContext))]
    [Migration("20221026152035_Creacion-Inicial")]
    partial class CreacionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ASP.NET_CRUD_example_2.Models.AlumnoDTO", b =>
                {
                    b.Property<int>("Alumno_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("alumno_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Alumno_id"));

                    b.Property<string>("Alumno_apellidos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alumno_apellidos");

                    b.Property<string>("Alumno_email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alumno_email");

                    b.Property<string>("Alumno_nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alumno_nombre");

                    b.HasKey("Alumno_id");

                    b.ToTable("alumnos", "public");
                });

            modelBuilder.Entity("ASP.NET_CRUD_example_2.Models.AsignaturaDTO", b =>
                {
                    b.Property<int>("Asignatura_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("asignatura_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Asignatura_id"));

                    b.Property<string>("Asignatura_nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asignatura_nombre");

                    b.HasKey("Asignatura_id");

                    b.ToTable("asignaturas", "public");
                });

            modelBuilder.Entity("ASP.NET_CRUD_example_2.Models.RelAlumAsigDTO", b =>
                {
                    b.Property<int>("RelAlumAsig_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("relAlumAsig_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RelAlumAsig_id"));

                    b.Property<int>("Alumno_id")
                        .HasColumnType("integer")
                        .HasColumnName("alumno_id");

                    b.Property<int>("Asignatura_id")
                        .HasColumnType("integer")
                        .HasColumnName("asignatura_id");

                    b.HasKey("RelAlumAsig_id");

                    b.HasIndex("Alumno_id");

                    b.HasIndex("Asignatura_id");

                    b.ToTable("relalumasig", "public");
                });

            modelBuilder.Entity("ASP.NET_CRUD_example_2.Models.RelAlumAsigDTO", b =>
                {
                    b.HasOne("ASP.NET_CRUD_example_2.Models.AlumnoDTO", "Alumno")
                        .WithMany("ListaRelAlumAsig")
                        .HasForeignKey("Alumno_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NET_CRUD_example_2.Models.AsignaturaDTO", "Asignatura")
                        .WithMany("ListaRelAlumAsig")
                        .HasForeignKey("Asignatura_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("ASP.NET_CRUD_example_2.Models.AlumnoDTO", b =>
                {
                    b.Navigation("ListaRelAlumAsig");
                });

            modelBuilder.Entity("ASP.NET_CRUD_example_2.Models.AsignaturaDTO", b =>
                {
                    b.Navigation("ListaRelAlumAsig");
                });
#pragma warning restore 612, 618
        }
    }
}
